-- 도서 관리 테이블이 추가
-- 개인별 렌탈현황의 도서코드는 도서 관리테이블의 FK
-- 개인별 렌탈현황의 최종여부는 삭제되고, 반납여부가 추가됨

DROP TABLE SS1010 CASCADE CONSTRAINTS PURGE;

DROP TABLE SS0010 CASCADE CONSTRAINTS PURGE;

CREATE TABLE SS0010
(
  C_CD           VARCHAR2(20)                NOT NULL,
  BOOK_CD        VARCHAR2(20)                NOT NULL,
  ISBN           VARCHAR2(60)                NULL,
  WRITER         VARCHAR2(100)               NULL,
  PUBLISHER      VARCHAR2(50)                NULL,
  PUBLISHED_DATE VARCHAR2(8)                 NULL,
  DUTY_CD        VARCHAR2(60)                NULL,
  INS_USER_ID    VARCHAR2(20)                NULL,
  MOD_USER_ID    VARCHAR2(20)                NULL,
  INS_GYMDHMS    TIMESTAMP(6) WITH TIME ZONE NULL,
  INS_YMDHMS     TIMESTAMP(6)                NULL,
  MOD_YMDHMS     TIMESTAMP(6)                NULL,
  MOD_GYMDHMS    TIMESTAMP(6) WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX PK_I_SS0010 ON SS0010
(C_CD   ASC,BOOK_CD   ASC);

ALTER TABLE SS0010
  ADD CONSTRAINT  PK_I_SS0010 PRIMARY KEY (C_CD,BOOK_CD);

COMMENT ON TABLE SS0010 IS '(SS0010)도서관리';

COMMENT ON COLUMN SS0010.C_CD IS '회사코드';
COMMENT ON COLUMN SS0010.BOOK_CD IS '도서코드';
COMMENT ON COLUMN SS0010.ISBN IS '국제표준_도서번호';
COMMENT ON COLUMN SS0010.WRITER IS '저자';
COMMENT ON COLUMN SS0010.PUBLISHER IS '출판사';
COMMENT ON COLUMN SS0010.PUBLISHED_DATE IS '발행일';
COMMENT ON COLUMN SS0010.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN SS0010.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN SS0010.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN SS0010.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN SS0010.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN SS0010.MOD_GYMDHMS IS '수정일시_현지';


-- ---------------------------------------------------------------------------------------------------------------

CREATE TABLE SS1010
(
  C_CD        VARCHAR2(20)                NOT NULL,
  EMP_ID      VARCHAR2(20)                NOT NULL,
  SEQ_NO      NUMBER      DEFAULT 0       NOT NULL,
  BOOK_CD     VARCHAR2(20)                NULL,
  STA_YMD     VARCHAR2(8)                 NULL,
  END_YMD     VARCHAR2(8)                 NULL,
  RETURN_YN   VARCHAR2(1) DEFAULT 'Y'     NULL
    CONSTRAINT yn_958676398 CHECK (RETURN_YN IN ('Y', 'N')),
  NOTE        VARCHAR2(1500)              NULL,
  INS_USER_ID VARCHAR2(20)                NULL,
  MOD_USER_ID VARCHAR2(20)                NULL,
  INS_YMDHMS  TIMESTAMP(6)                NULL,
  INS_GYMDHMS TIMESTAMP(6) WITH TIME ZONE NULL,
  MOD_YMDHMS  TIMESTAMP(6)                NULL,
  MOD_GYMDHMS TIMESTAMP(6) WITH TIME ZONE NULL,
  CONSTRAINT NI_SS0010_SS1010 FOREIGN KEY (C_CD, BOOK_CD) REFERENCES SS0010 (C_CD, BOOK_CD) ON DELETE SET NULL
);

CREATE UNIQUE INDEX PK_I_SS1010 ON SS1010
(C_CD   ASC,EMP_ID   ASC,SEQ_NO   ASC);

ALTER TABLE SS1010
  ADD CONSTRAINT  PK_I_SS1010 PRIMARY KEY (C_CD,EMP_ID,SEQ_NO);

COMMENT ON TABLE SS1010 IS '(SS1010)개인별도서대여현황';

COMMENT ON COLUMN SS1010.C_CD IS '회사코드';
COMMENT ON COLUMN SS1010.EMP_ID IS '사번';
COMMENT ON COLUMN SS1010.SEQ_NO IS '일련번호';
COMMENT ON COLUMN SS1010.BOOK_CD IS '도서코드';
COMMENT ON COLUMN SS1010.STA_YMD IS '시작일';
COMMENT ON COLUMN SS1010.END_YMD IS '종료일';
COMMENT ON COLUMN SS1010.RETURN_YN IS '반납여부';
COMMENT ON COLUMN SS1010.NOTE IS '비고';
COMMENT ON COLUMN SS1010.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN SS1010.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN SS1010.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN SS1010.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN SS1010.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN SS1010.MOD_GYMDHMS IS '수정일시_현지';