SELECT DISTINCT @B_COLUMN_NM@ CD
  FROM (
SELECT M.C_CD,
       M.EMP_ID,
       M.AGE,
       M.GENDER_TYPE,
       M.ORG_ID,
       M.EMP_GRADE_CD,
       M.DUTY_CD,
       (SELECT T1.GIV_STD_ID FROM PR3010 T1 WHERE T1.C_CD = :C_CD AND T1.GIV_YY = :GIV_YY) GIV_STD_ID,
       (SELECT T1.GIV_STD_NM FROM PR3010 T1 WHERE T1.C_CD = :C_CD AND T1.GIV_YY = :GIV_YY) GIV_STD_NM,
       CD_UNIF_GENDER_TYPE.CD_NM UNIF_GENDER_TYPE_NM,
       CD_UNIF_BRAND.CD_NM UNIF_BRAND_NM,
       CD_UNIF_SIZE.CD_NM UNIF_SIZE_NM,
       CD_UNIF_TYPE.CD_NM UNIF_TYPE_NM,
       CD_GENDER_TYPE.CD_NM GENDER_TYPE_NM,
       CD_EMP_GRADE_CD.CD_NM EMP_GRADE_NM,
       CD_DUTY_CD.CD_NM DUTY_NM,
       NVL(CD_ORG_ID.OBJ_NM, M.ORG_NM) ORG_NM,
       ORGTREE.DP_ORDER ORG_ORDER,
       ORGTREE.TLEVEL ORG_LEVEL,
       'X'
  FROM (
       SELECT T1.C_CD,
              T1.EMP_ID,
              TRUNC(MONTHS_BETWEEN2(CURRENT_TIMESTAMP,TO_DATE(DECODE(F_ISYMD(T1.BIRTH_YMD),'T',T1.BIRTH_YMD),'YYYYMMDD'))/12) AGE,
              T1.GENDER_TYPE,
              T2.ORG_ID,
              T2.ORG_NM,
              T2.EMP_GRADE_CD,
              T2.DUTY_CD,
              T2.DUTY_NM
         FROM VR_PA1010 T1,
              PA1020 T2
        WHERE 1=1
          AND T2.C_CD = T1.C_CD
          AND T2.EMP_ID = T1.EMP_ID
          AND :YMD BETWEEN T2.STA_YMD AND T2.END_YMD
          AND T2.LAST_YN = 'Y'
          AND T2.STAT_CD LIKE '1%'
          AND T1.C_CD = :C_CD
) M,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = 'PR3020' AND T1.LANG_TYPE = :LANG_TYPE) CD_UNIF_BRAND,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = '00020' AND T1.LANG_TYPE = :LANG_TYPE) CD_UNIF_GENDER_TYPE,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = 'PR3060' AND T1.LANG_TYPE = :LANG_TYPE) CD_UNIF_TYPE,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = 'PR3030' AND T1.LANG_TYPE = :LANG_TYPE) CD_UNIF_SIZE,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = '00020' AND T1.LANG_TYPE = :LANG_TYPE) CD_GENDER_TYPE,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = '/SY03' AND T1.LANG_TYPE = :LANG_TYPE) CD_EMP_GRADE_CD,
       (SELECT T1.C_CD, T1.CD, T1.CD_NM FROM SY9820 T1 WHERE T1.IDX_CD = '/SY05' AND T1.LANG_TYPE = :LANG_TYPE) CD_DUTY_CD,
       (SELECT T1.C_CD, T1.OBJ_ID, T2.OBJ_NM FROM SY3010 T1, SY9910 T2 WHERE T1.OBJ_TYPE = 'O'  AND :YMD BETWEEN T1.STA_YMD AND T1.END_YMD AND T2.C_CD(+) = T1.C_CD AND T2.OBJ_TYPE(+) = T1.OBJ_TYPE AND T2.OBJ_ID(+) = T1.OBJ_ID AND T2.STA_YMD = T1.STA_YMD AND T2.LANG_TYPE(+) = :LANG_TYPE) CD_ORG_ID,
       (
        SELECT T1.C_CD,
               T1.OBJ_ID ORG_ID,
               LEVEL TLEVEL,
               ROWNUM DP_ORDER
          FROM (SELECT T1.* FROM SY3020 T1 WHERE T1.C_CD = :C_CD AND T1.OBJ_TYPE IN (SELECT A.OBJ_TYPE FROM SY3080 A WHERE A.C_CD = :C_CD AND A.OBJ_TREE_TYPE = 'ORGTREE') AND :YMD BETWEEN T1.STA_YMD AND T1.END_YMD) T1
         START WITH
               (T1.C_CD, T1.OBJ_TYPE, T1.OBJ_ID) IN
               (SELECT C_CD, ROOT_OBJ_TYPE, ROOT_OBJ_ID FROM SY3070 WHERE OBJ_TREE_TYPE = 'ORGTREE' AND :YMD BETWEEN STA_YMD AND END_YMD)
           AND :YMD BETWEEN T1.STA_YMD AND T1.END_YMD
         CONNECT BY
               PRIOR T1.C_CD = T1.C_CD
           AND PRIOR T1.OBJ_TYPE = T1.PAR_OBJ_TYPE
           AND PRIOR T1.OBJ_ID = T1.PAR_OBJ_ID
         ORDER SIBLINGS BY
               T1.SEQ_NO
       ) ORGTREE,
       (
         SELECT T1.C_CD,
                T1.GIV_STD_ID,
                T2.UNIF_CD,
                T2.UNIF_BRAND,
                T2.UNIF_SIZE,
                T2.UNIF_TYPE,
                T2.GENDER_TYPE
         FROM PR3010 T1,
              PR3110 T2
        WHERE 1=1
          AND T1.GIV_STD_ID = T2.GIV_STD_ID
          AND T1.GIV_YY = :GIV_YY
          AND T2.C_CD = T1.C_CD
          AND T1.C_CD = :C_CD
           ) U
 WHERE 1=1
   AND CD_UNIF_BRAND.C_CD(+) = U.C_CD
   AND CD_UNIF_BRAND.CD(+) = U.UNIF_BRAND
   AND CD_UNIF_SIZE.C_CD(+) = U.C_CD
   AND CD_UNIF_SIZE.CD(+) = U.UNIF_SIZE
   AND CD_UNIF_TYPE.C_CD(+) = U.C_CD
   AND CD_UNIF_TYPE.CD(+) = U.UNIF_TYPE
   AND CD_UNIF_GENDER_TYPE.C_CD(+) = U.C_CD
   AND CD_UNIF_GENDER_TYPE.CD(+) = U.GENDER_TYPE
   AND CD_GENDER_TYPE.C_CD(+) = M.C_CD
   AND CD_GENDER_TYPE.CD(+) = M.GENDER_TYPE
   AND CD_EMP_GRADE_CD.C_CD(+) = M.C_CD
   AND CD_EMP_GRADE_CD.CD(+) = M.EMP_GRADE_CD
   AND CD_DUTY_CD.C_CD(+) = M.C_CD
   AND CD_DUTY_CD.CD(+) = M.DUTY_CD
   AND CD_ORG_ID.C_CD(+) = M.C_CD
   AND CD_ORG_ID.OBJ_ID(+) = M.ORG_ID
   AND ORGTREE.C_CD(+) = M.C_CD
   AND ORGTREE.ORG_ID(+) = M.ORG_ID
       )
ORDER BY 1