DROP TABLE PR3010 CASCADE CONSTRAINTS PURGE;
CREATE TABLE PR3010
(
  C_CD        VARCHAR2(20) NOT NULL,
  GIV_STD_ID  VARCHAR2(60) NOT NULL,
  GIV_STD_NM  VARCHAR2(300),
  GIV_YY      VARCHAR2(4),
  GIV_TYPE    VARCHAR2(20),
  GIV_TIME_CD VARCHAR2(20),
  STA_YMD     VARCHAR2(8),
  END_YMD     VARCHAR2(8),
  GIV_PGR_YN  VARCHAR2(1) DEFAULT 'N'
    CONSTRAINT PR_000000001
      CHECK (GIV_PGR_YN IN ('Y', 'N')),
  GIV_END     VARCHAR2(20),
  NOTI_SBJ    CLOB,
  NOTE        VARCHAR2(1000),
  INS_USER_ID VARCHAR2(20),
  INS_YMDHMS  TIMESTAMP(6),
  MOD_USER_ID VARCHAR2(20),
  MOD_YMDHMS  TIMESTAMP(6),
  INS_GYMDHMS TIMESTAMP(6) WITH TIME ZONE,
  MOD_GYMDHMS TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_I_PR3010
    PRIMARY KEY (C_CD, GIV_STD_ID)
);
COMMENT ON TABLE PR3010 IS '(PR3010)유니폼지급회차관리';

COMMENT ON COLUMN PR3010.C_CD IS '회사코드';
COMMENT ON COLUMN PR3010.GIV_STD_ID IS '지급회차ID';
COMMENT ON COLUMN PR3010.GIV_STD_NM IS '지급회차명';
COMMENT ON COLUMN PR3010.GIV_YY IS '지급년도';
COMMENT ON COLUMN PR3010.GIV_TYPE IS '지급유형코드';
COMMENT ON COLUMN PR3010.GIV_TIME_CD IS '지급회차코드';
COMMENT ON COLUMN PR3010.STA_YMD IS '시작일';
COMMENT ON COLUMN PR3010.END_YMD IS '종료일';
COMMENT ON COLUMN PR3010.GIV_PGR_YN IS '신청허가여부';
COMMENT ON COLUMN PR3010.GIV_END IS '지급종료여부';
COMMENT ON COLUMN PR3010.NOTI_SBJ IS '공지사항';
COMMENT ON COLUMN PR3010.NOTE IS '비고';
COMMENT ON COLUMN PR3010.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN PR3010.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN PR3010.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN PR3010.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN PR3010.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN PR3010.MOD_GYMDHMS IS '수정일시_현지';