-- 노트북 관리 테이블이 추가됨
-- 개인별 렌탈현황의 장비코드는 노트북 관리테이블의 FK
-- 개인별 렌탈현황의 최종여부는 삭제되고, 반납여부가 추가됨


DROP TABLE ZZ1010 CASCADE CONSTRAINTS PURGE;

DROP TABLE ZZ0010 CASCADE CONSTRAINTS PURGE;

CREATE TABLE ZZ0010
(
  C_CD                 VARCHAR2(20) NOT NULL ,
  EQUIP_CD             VARCHAR2(20) NOT NULL ,
  BRAND_NM             VARCHAR2(100) NULL ,
  CPU                  VARCHAR2(100) NULL ,
  RAM                  NUMBER NULL ,
  SSD                  NUMBER NULL ,
  INS_USER_ID          VARCHAR2(20) NULL ,
  MOD_USER_ID          VARCHAR2(20) NULL ,
  INS_GYMDHMS          TIMESTAMP(6) WITH TIME ZONE NULL ,
  INS_YMDHMS           TIMESTAMP(6) NULL ,
  MOD_YMDHMS           TIMESTAMP(6) NULL ,
  MOD_GYMDHMS          TIMESTAMP(6) WITH TIME ZONE NULL 
);

CREATE UNIQUE INDEX PK_I_ZZ0010 ON ZZ0010
(C_CD   ASC,EQUIP_CD   ASC);

ALTER TABLE ZZ0010
  ADD CONSTRAINT  PK_I_ZZ0010 PRIMARY KEY (C_CD,EQUIP_CD);

CREATE TABLE ZZ1010
(
  C_CD                 VARCHAR2(20) NOT NULL ,
  EMP_ID               VARCHAR2(20) NOT NULL ,
  SEQ_NO               NUMBER DEFAULT  0  NOT NULL ,
  EQUIP_CD             VARCHAR2(20) NULL ,
  STA_YMD              VARCHAR2(8) NULL ,
  END_YMD              VARCHAR2(8) NULL ,
  RETURN_YN            VARCHAR2(1) DEFAULT  'Y'  NULL  CONSTRAINT  yn_958676397 CHECK (RETURN_YN IN ('Y', 'N')),
  NOTE                 VARCHAR2(1500) NULL ,
  INS_USER_ID          VARCHAR2(20) NULL ,
  MOD_USER_ID          VARCHAR2(20) NULL ,
  INS_YMDHMS           TIMESTAMP(6) NULL ,
  INS_GYMDHMS          TIMESTAMP(6) WITH TIME ZONE NULL ,
  MOD_YMDHMS           TIMESTAMP(6) NULL ,
  MOD_GYMDHMS          TIMESTAMP(6) WITH TIME ZONE NULL ,
CONSTRAINT NI_ZZ0010_ZZ1010 FOREIGN KEY (C_CD, EQUIP_CD) REFERENCES ZZ0010 (C_CD, EQUIP_CD) ON DELETE SET NULL
);

CREATE UNIQUE INDEX PK_I_ZZ1010 ON ZZ1010
(C_CD   ASC,EMP_ID   ASC,SEQ_NO   ASC);

ALTER TABLE ZZ1010
  ADD CONSTRAINT  PK_I_ZZ1010 PRIMARY KEY (C_CD,EMP_ID,SEQ_NO);


COMMENT ON TABLE ZZ0010 IS '(ZZ0010)노트북관리';

COMMENT ON COLUMN ZZ0010.C_CD IS '회사코드';
COMMENT ON COLUMN ZZ0010.EQUIP_CD IS '장비코드';
COMMENT ON COLUMN ZZ0010.BRAND_NM IS '브랜드';
COMMENT ON COLUMN ZZ0010.CPU IS 'CPU';
COMMENT ON COLUMN ZZ0010.RAM IS 'RAM';
COMMENT ON COLUMN ZZ0010.SSD IS 'SSD';
COMMENT ON COLUMN ZZ0010.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN ZZ0010.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN ZZ0010.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN ZZ0010.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN ZZ0010.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN ZZ0010.MOD_GYMDHMS IS '수정일시_현지';

COMMENT ON TABLE ZZ1010 IS '(ZZ1010)개인별노트북렌탈현황';

COMMENT ON COLUMN ZZ1010.C_CD IS '회사코드';
COMMENT ON COLUMN ZZ1010.EMP_ID IS '사번';
COMMENT ON COLUMN ZZ1010.SEQ_NO IS '일련번호';
COMMENT ON COLUMN ZZ1010.EQUIP_CD IS '장비코드';
COMMENT ON COLUMN ZZ1010.STA_YMD IS '시작일';
COMMENT ON COLUMN ZZ1010.END_YMD IS '종료일';
COMMENT ON COLUMN ZZ1010.RETURN_YN IS '반납여부';
COMMENT ON COLUMN ZZ1010.NOTE IS '비고';
COMMENT ON COLUMN ZZ1010.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN ZZ1010.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN ZZ1010.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN ZZ1010.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN ZZ1010.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN ZZ1010.MOD_GYMDHMS IS '수정일시_현지';

ALTER TABLE ZZ0010 DROP COLUMN BRAND_NM;
ALTER TABLE ZZ0010 ADD BRAND_CD VARCHAR2(60BYTE);