CREATE TABLE ZZ1010
(
C_CD VARCHAR2(20) NOT NULL ,
EMP_ID VARCHAR2(20) NOT NULL ,
SEQ_NO NUMBER DEFAULT 0 NOT NULL ,
EQUIP_CD VARCHAR2(100) NULL ,
STA_YMD VARCHAR2(8) NULL ,
END_YMD VARCHAR2(8) NULL ,
LAST_YN VARCHAR2(1) DEFAULT 'Y' NULL CONSTRAINT yn_886220726 CHECK (LAST_YN IN ('Y', 'N')),
NOTE VARCHAR2(1500) NULL ,
INS_USER_ID VARCHAR2(20) NULL ,
MOD_USER_ID VARCHAR2(20) NULL ,
INS_YMDHMS TIMESTAMP(6) NULL ,
INS_GYMDHMS TIMESTAMP(6) WITH TIME ZONE NULL ,
MOD_YMDHMS TIMESTAMP(6) NULL ,
MOD_GYMDHMS TIMESTAMP(6) WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX PK_I_ZZ1010 ON ZZ1010
(C_CD ASC,EMP_ID ASC,SEQ_NO ASC);

ALTER TABLE ZZ1010
ADD CONSTRAINT PK_I_ZZ1010 PRIMARY KEY (C_CD,EMP_ID,SEQ_NO);


COMMENT ON TABLE ZZ1010 IS '(ZZ1010)개인별노트북렌탈현황';

COMMENT ON COLUMN ZZ1010.C_CD IS '회사코드';
COMMENT ON COLUMN ZZ1010.EMP_ID IS '사번';
COMMENT ON COLUMN ZZ1010.SEQ_NO IS '일련번호';
COMMENT ON COLUMN ZZ1010.EQUIP_CD IS '장비코드';
COMMENT ON COLUMN ZZ1010.STA_YMD IS '시작일';
COMMENT ON COLUMN ZZ1010.END_YMD IS '종료일';
COMMENT ON COLUMN ZZ1010.LAST_YN IS '최종여부';
COMMENT ON COLUMN ZZ1010.NOTE IS '비고';
COMMENT ON COLUMN ZZ1010.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN ZZ1010.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN ZZ1010.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN ZZ1010.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN ZZ1010.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN ZZ1010.MOD_GYMDHMS IS '수정일시_현지';