DROP TABLE PR3210 CASCADE CONSTRAINTS PURGE;
CREATE TABLE PR3210
(
  C_CD         VARCHAR2(20)                NOT NULL,
  EMP_ID       VARCHAR2(60)                NOT NULL,
  GIV_STD_ID   VARCHAR2(60)                NOT NULL,
  EMP_NM       VARCHAR2(60)                NULL,
  GENDER_TYPE  VARCHAR2(60)                NULL,
  ORG_ID       VARCHAR2(60)                NULL,
  ORG_NM       VARCHAR2(60)                NULL,
  EMP_GRADE_CD VARCHAR2(60)                NULL,
  APPL_ID      VARCHAR2(60)                NULL,
  INS_USER_ID  VARCHAR2(20)                NULL,
  MOD_USER_ID  VARCHAR2(20)                NULL,
  INS_GYMDHMS  TIMESTAMP(6) WITH TIME ZONE NULL,
  INS_YMDHMS   TIMESTAMP(6)                NULL,
  MOD_YMDHMS   TIMESTAMP(6)                NULL,
  MOD_GYMDHMS  TIMESTAMP(6) WITH TIME ZONE NULL,
  CONSTRAINT PK_I_PR3210
    PRIMARY KEY (C_CD, EMP_ID, GIV_STD_ID),
  CONSTRAINT NI_PR3010_PR3210
    FOREIGN KEY (C_CD, GIV_STD_ID) REFERENCES PR3010 ON DELETE CASCADE,
  CONSTRAINT NI_SY7010_PR3210
    FOREIGN KEY (C_CD, APPL_ID) REFERENCES SY7010 ON DELETE CASCADE,
  CONSTRAINT NI_PA1010_PR3210
    FOREIGN KEY (C_CD, EMP_ID) REFERENCES PA1010 ON DELETE CASCADE
);

COMMENT ON TABLE PR3210 IS '(PR3210)유니폼지급대상자관리';

COMMENT ON COLUMN PR3210.C_CD IS '회사코드';
COMMENT ON COLUMN PR3210.EMP_ID IS '사번';
COMMENT ON COLUMN PR3210.GIV_STD_ID IS '지급회차ID';
COMMENT ON COLUMN PR3210.EMP_NM IS '사원이름';
COMMENT ON COLUMN PR3210.GENDER_TYPE IS '성별';
COMMENT ON COLUMN PR3210.ORG_ID IS '조직코드';
COMMENT ON COLUMN PR3210.ORG_NM IS '조직명';
COMMENT ON COLUMN PR3210.EMP_GRADE_CD IS '직급코드';
COMMENT ON COLUMN PR3210.APPL_ID IS '신청서번호';
COMMENT ON COLUMN PR3210.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN PR3210.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN PR3210.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN PR3210.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN PR3210.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN PR3210.MOD_GYMDHMS IS '수정일시_현지';