DROP TABLE PR3310 CASCADE CONSTRAINTS PURGE;
CREATE TABLE PR3310
(
  C_CD                  VARCHAR2(20)          NOT NULL,
  APPL_ID               VARCHAR2(60)          NOT NULL,
  EMP_ID                VARCHAR2(60),
  GIV_STD_ID            VARCHAR2(60)          NOT NULL,
  GIV_YMD               VARCHAR2(8),
  UNIF_CNT              NUMBER      DEFAULT 1 NOT NULL,
  NOTE                  VARCHAR2(1500),
  INS_USER_ID           VARCHAR2(20),
  INS_YMDHMS            TIMESTAMP(6),
  MOD_USER_ID           VARCHAR2(20),
  MOD_YMDHMS            TIMESTAMP(6),
  INS_GYMDHMS           TIMESTAMP(6) WITH TIME ZONE,
  MOD_GYMDHMS           TIMESTAMP(6) WITH TIME ZONE,

  CONSTRAINT PK_I_PR3310
    PRIMARY KEY (C_CD, APPL_ID, GIV_STD_ID),
  CONSTRAINT NI_SY7010_PR3310
    FOREIGN KEY (C_CD, APPL_ID) REFERENCES SY7010 ON DELETE CASCADE,
  CONSTRAINT NI_PA1010_PR3310
    FOREIGN KEY (C_CD, EMP_ID) REFERENCES PA1010 ON DELETE CASCADE,
  CONSTRAINT NI_PR3210_PR3310
    FOREIGN KEY (C_CD, GIV_STD_ID) REFERENCES PR3210 ON DELETE CASCADE
);
COMMENT ON TABLE PR3310 IS '(PR3310)유니폼신청';

COMMENT ON COLUMN PR3310.C_CD IS '회사코드';
COMMENT ON COLUMN PR3310.APPL_ID IS '신청서ID';
COMMENT ON COLUMN PR3310.EMP_ID IS '신청서ID';
COMMENT ON COLUMN PR3310.GIV_STD_ID IS '선물유형';
COMMENT ON COLUMN PR3310.GIV_YMD IS '유니폼수령일';
COMMENT ON COLUMN PR3310.UNIF_CNT IS '유니폼수량';
COMMENT ON COLUMN PR3310.NOTE IS '비고';
COMMENT ON COLUMN PR3310.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN PR3310.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN PR3310.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN PR3310.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN PR3310.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN PR3310.MOD_GYMDHMS IS '수정일시_현지';