CREATE TABLE PR3410
(
    C_CD        VARCHAR2(20)     NOT NULL,
    SEQ_NO      NUMBER DEFAULT 0 NOT NULL,
    DATA_ID     VARCHAR2(60)     NOT NULL,
    APPL_ID     VARCHAR2(60)     NULL,
    EMP_ID      VARCHAR2(20)     NULL,
    EMP_NM      VARCHAR2(60)     NULL,
    ORG_ID      VARCHAR2(60)     NULL,
    GIV_YMD     VARCHAR2(8)      NULL,
    ORG_NM      VARCHAR2(60)     NULL,
    GIV_YN      VARCHAR2(20)     NULL,
    GIV_STD_ID  VARCHAR2(60)     NULL,
    NOTE        VARCHAR2(4000)   NULL,
    IN_TYPE     VARCHAR2(20)     NULL,
    INS_USER_ID VARCHAR2(20)     NULL,
    INS_YMDHMS  TIMESTAMP(6)     NULL,
    MOD_USER_ID VARCHAR2(20)     NULL,
    MOD_YMDHMS  TIMESTAMP(6)     NULL,
    INS_GYMDHMS TIMESTAMP(6)     NULL,
    MOD_GYMDHMS TIMESTAMP(6)     NULL,
    CONSTRAINT PR3410_PK
        PRIMARY KEY (C_CD, SEQ_NO, DATA_ID),
    CONSTRAINT NI_SY7010_PR3410
        FOREIGN KEY (C_CD, APPL_ID) REFERENCES SY7010 ON DELETE CASCADE
);

COMMENT ON TABLE PR3410 IS '(PR3410)유니폼신청관리';

COMMENT ON TABLE PR3410 IS '(PR3410)유니폼신청관리';
COMMENT ON COLUMN PR3410.C_CD IS '회사코드';
COMMENT ON COLUMN PR3410.SEQ_NO IS '일련번호';
COMMENT ON COLUMN PR3410.DATA_ID IS '자료ID';
COMMENT ON COLUMN PR3410.APPL_ID IS '신청서ID';
COMMENT ON COLUMN PR3410.EMP_ID IS '사번';
COMMENT ON COLUMN PR3410.EMP_NM IS '사원이름';
COMMENT ON COLUMN PR3410.ORG_ID IS '조직코드';
COMMENT ON COLUMN PR3410.GIV_YMD IS '유니폼수령일';
COMMENT ON COLUMN PR3410.ORG_NM IS '조직명';
COMMENT ON COLUMN PR3410.GIV_YN IS '수령완료여부';
COMMENT ON COLUMN PR3410.GIV_STD_ID IS '지급회차ID';
COMMENT ON COLUMN PR3410.NOTE IS '비고';
COMMENT ON COLUMN PR3410.IN_TYPE IS '입력유형';
COMMENT ON COLUMN PR3410.INS_USER_ID IS '입력자ID';
COMMENT ON COLUMN PR3410.INS_YMDHMS IS '입력일시';
COMMENT ON COLUMN PR3410.MOD_USER_ID IS '작업자ID';
COMMENT ON COLUMN PR3410.MOD_YMDHMS IS '수정일시';
COMMENT ON COLUMN PR3410.INS_GYMDHMS IS '입력일시_현지';
COMMENT ON COLUMN PR3410.MOD_GYMDHMS IS '수정일시_현지';